<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-12 at 00:49:51.
 */
class ApiSkillsControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApiSkillsController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ApiSkillsController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ApiSkillsController::actionGetCurrentUserSkills
     * @todo   Implement testActionGetCurrentUserSkills().
     */
    public function testActionGetCurrentUserSkills() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiSkillsController::actionModifyCurrentUserSkill
     * @todo   Implement testActionModifyCurrentUserSkill().
     */
    public function testActionModifyCurrentUserSkill() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
