<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-18 at 00:57:43.
 */
class ApiUserControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApiUserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ApiUserController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ApiUserController::actionLoginUser
     * @todo   Implement testActionLoginUser().
     */
    public function testActionLoginUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiUserController::actionGetUser
     * @todo   Implement testActionGetUser().
     */
    public function testActionGetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiUserController::actionRegisterUser
     * @todo   Implement testActionRegisterUser().
     */
    public function testActionRegisterUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiUserController::actionModifyUser
     * @todo   Implement testActionModifyUser().
     */
    public function testActionModifyUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
