LEARZ_SKILL_ID_LANGUAGES = "1";
LEARZ_SKILL_ID_ENGLISH = "2";
LEARZ_SKILL_ID_ENGLISH_IDIOMS = "3";
LEARZ_SKILL_ID_ENGLISH_SLANG = "4";
LEARZ_SKILL_ID_ENGLISH_VOCABULARY = "5";

function Skill(id, name, parent_id, is_leaf) {
    this.id = id;
    this.name = name;
    this.parent_id = parent_id;
    this.is_leaf = is_leaf;
}

LEARZ_SKILLS_MAP = {};
LEARZ_SKILLS_MAP[LEARZ_SKILL_ID_LANGUAGES] =
    new Skill(LEARZ_SKILL_ID_LANGUAGES, 'Languages', null, false);
LEARZ_SKILLS_MAP[LEARZ_SKILL_ID_ENGLISH] =
    new Skill(LEARZ_SKILL_ID_ENGLISH, 'English', LEARZ_SKILL_ID_LANGUAGES, null, false);
LEARZ_SKILLS_MAP[LEARZ_SKILL_ID_ENGLISH_IDIOMS] =
    new Skill(LEARZ_SKILL_ID_ENGLISH_IDIOMS, 'Idioms', LEARZ_SKILL_ID_ENGLISH, true);
LEARZ_SKILLS_MAP[LEARZ_SKILL_ID_ENGLISH_SLANG] =
    new Skill(LEARZ_SKILL_ID_ENGLISH_SLANG, 'Slang', LEARZ_SKILL_ID_ENGLISH, true);
LEARZ_SKILLS_MAP[LEARZ_SKILL_ID_ENGLISH_VOCABULARY] =
    new Skill(LEARZ_SKILL_ID_ENGLISH_VOCABULARY, 'Vocabulary', LEARZ_SKILL_ID_ENGLISH, true);