<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-12 at 00:42:30.
 */
class UserSkillsServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserSkillsService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserSkillsService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserSkillsService::getUserSkills
     * @todo   Implement testGetUserSkills().
     */
    public function testGetUserSkills() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserSkillsService::setUserSkillValue
     * @todo   Implement testSetUserSkillValue().
     */
    public function testSetUserSkillValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
