<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 15:44:33.
 */
class AuthIdentityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AuthIdentity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new AuthIdentity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AuthIdentity::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
