<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-29 at 04:02:43.
 */
class CustomerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Customer
     */
    protected $customer;
    protected $customerUser;
    protected $friend1;
    protected $friend2;
    protected $friend3;

    protected function mkCustomer($id, $friends, &$user = NULL) {
        $user = new AuthentificatedUser($id . "@example.com",
                "name" . $id, "surname" . $id, FALSE, $id,
                new UserRole(UserRole::CUSTOMER),
                "password" . $id, $id);
        return new Customer($user, $friends);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->friend1 = $this->mkCustomer("1", array());
        $this->friend2 = $this->mkCustomer("2", array());
        $this->friend3 = $this->mkCustomer("3", array());
        $this->customer = $this->mkCustomer("0", array($this->friend1,
            $this->friend2, $this->friend3), $this->customerUser);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\Customer::getUser
     */
    public function testGetUser() {
        assert($this->customer->getUser() == $this->customerUser);
    }

    /**
     * @covers model\Customer::getFriends
     * @covers model\Customer::__construct
     * @covers model\Customer::setFriends
     */
    public function testGetFriends() {
        assert($this->customer->getFriends()[1] == $this->friend1);
        assert($this->customer->getFriends()[2] == $this->friend2);
        assert($this->customer->getFriends()[3] == $this->friend3);
    }

    public function testChangesTracking() {
        $changes = $this->customer->getValueChanges();
        assert(empty($changes));
    }
}
