<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-29 at 04:02:43.
 */
class UserRoleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UserRole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserRole(UserRole::CUSTOMER);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\UserRole::getVal
     * @todo   Implement testGetVal().
     */
    public function testGetVal() {
        // Remove the following lines when you implement this test.
        assert($this->object->getVal() == UserRole::CUSTOMER);
    }

}
