<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 15:43:17.
 */
class HybridAuthIdentityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HybridAuthIdentity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new HybridAuthIdentity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HybridAuthIdentity::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HybridAuthIdentity::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HybridAuthIdentity::getAdapter
     * @todo   Implement testGetAdapter().
     */
    public function testGetAdapter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HybridAuthIdentity::getLoginProvider
     * @todo   Implement testGetLoginProvider().
     */
    public function testGetLoginProvider() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HybridAuthIdentity::getLoginProviderIdentifier
     * @todo   Implement testGetLoginProviderIdentifier().
     */
    public function testGetLoginProviderIdentifier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
