<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 15:44:11.
 */
class PostgresHybridAuthStorageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PostgresHybridAuthStorage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new PostgresHybridAuthStorage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PostgresHybridAuthStorage::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PostgresHybridAuthStorage::saveHAuthRecord
     * @todo   Implement testSaveHAuthRecord().
     */
    public function testSaveHAuthRecord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PostgresHybridAuthStorage::getAuthentificatedUser
     * @todo   Implement testGetAuthentificatedUser().
     */
    public function testGetAuthentificatedUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PostgresHybridAuthStorage::getUserHAuthRecords
     * @todo   Implement testGetUserHAuthRecords().
     */
    public function testGetUserHAuthRecords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
