<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Saturday 19th of October 2013 11:26:37 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
	array(
		//"base_url" => "http://localhost/vbm/hybridauth_new/hybridauth-2.1.2/hybridauth",
		"base_url" => "http://phrenlabs.co.uk/VBM/hybridauth/",


		"providers" => array (
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array (
				"enabled" => true
			),

			"Yahoo" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "880363572239.apps.googleusercontent.com", "secret" => "UaYnNkOZnRWj1fkzKP0gqjTI" )
			),

			"Facebook" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "744858745540842", "secret" => "6e356249ac1cf93da1b8694de00f9d9c" )
			),

			"Twitter" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "LwiRbzXDGhzvhuvPFLRkg", "secret" => "LMcDHie2pNJ9N8xNa4EfNaIqHKqDB27R5sOylu8Ci8w" )
			),

			// windows live
			"Live" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"MySpace" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"LinkedIn" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
