<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-18 at 00:57:43.
 */
class ApiFriendsControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApiFriendsController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ApiFriendsController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ApiFriendsController::actionGetFriends
     * @todo   Implement testActionGetFriends().
     */
    public function testActionGetFriends() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiFriendsController::actionAddFriend
     * @todo   Implement testActionAddFriend().
     */
    public function testActionAddFriend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiFriendsController::actionDeleteFriend
     * @todo   Implement testActionDeleteFriend().
     */
    public function testActionDeleteFriend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
