<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-18 at 00:57:43.
 */
class ApiMessagingControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApiMessagingController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ApiMessagingController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ApiMessagingController::actionGetMessages
     * @todo   Implement testActionGetMessages().
     */
    public function testActionGetMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApiMessagingController::actionSendMessage
     * @todo   Implement testActionSendMessage().
     */
    public function testActionSendMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
