<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 14:38:00.
 */
class HandlerControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HandlerController
     */
    protected $controller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->controller = new HandlerController(0);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DefaultController::actionIndex
     * @todo   Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DefaultController::actionCallback
     * @todo   Implement testActionCallback().
     */
    public function testActionCallback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DefaultController::actionUnlink
     * @todo   Implement testActionUnlink().
     */
    public function testActionUnlink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
